#!/bin/bash
set -e

docker run --rm -p 3001:3001 \
  -e PORT=3001 \
  -e SUPABASE_URL=YOUR_SUPABASE_URL \
  -e SUPABASE_SERVICE_ROLE_KEY=YOUR_SUPABASE_SERVICE_ROLE_KEY \
  -e ANTHROPIC_API_KEY=YOUR_ANTHROPIC_API_KEY \
  -e DATABASE_URL=YOUR_DATABASE_URL \
  -e JWT_SECRET=YOUR_JWT_SECRET \
  -e AWS_ACCESS_KEY_ID=YOUR_AWS_ACCESS_KEY_ID \
  -e AWS_SECRET_ACCESS_KEY=YOUR_AWS_SECRET_ACCESS_KEY \
  -e AWS_REGION=us-east-2 \
  -e S3_BUCKET_NAME=fieldside-logos \
  -e ECR_REGISTRY=YOUR_ECR_REGISTRY \
  -e ECR_REPOSITORY=fieldside-server \
  -e RESEND_API_KEY=YOUR_RESEND_API_KEY \
  fieldside-server
