-- Step 1: Add body_parts column
ALTER TABLE public.exercises ADD COLUMN IF NOT EXISTS body_parts text;

-- Step 2: Assign body parts to the 100 seeded exercises
-- (comma-separated; exercises with multiple body parts will appear in multiple sections)

UPDATE public.exercises SET body_parts = 'Knee'                              WHERE name = 'Quad Sets';
UPDATE public.exercises SET body_parts = 'Knee, Hip'                         WHERE name = 'Straight Leg Raises';
UPDATE public.exercises SET body_parts = 'Knee'                              WHERE name = 'Short Arc Quads';
UPDATE public.exercises SET body_parts = 'Knee'                              WHERE name = 'Terminal Knee Extension (TKE)';
UPDATE public.exercises SET body_parts = 'Knee'                              WHERE name = 'Heel Slides';
UPDATE public.exercises SET body_parts = 'Knee, Hip'                         WHERE name = 'Wall Squats (Wall Sit)';
UPDATE public.exercises SET body_parts = 'Knee, Hip'                         WHERE name = 'Mini Squats';
UPDATE public.exercises SET body_parts = 'Knee, Hip'                         WHERE name = 'Step Ups';
UPDATE public.exercises SET body_parts = 'Knee, Hip'                         WHERE name = 'Lateral Step Ups';
UPDATE public.exercises SET body_parts = 'Knee, Hip'                         WHERE name = 'Reverse Lunges';
UPDATE public.exercises SET body_parts = 'Knee, Hip'                         WHERE name = 'Walking Lunges';
UPDATE public.exercises SET body_parts = 'Knee, Hip'                         WHERE name = 'Bulgarian Split Squat';
UPDATE public.exercises SET body_parts = 'Knee, Hip'                         WHERE name = 'Nordic Hamstring Curls';
UPDATE public.exercises SET body_parts = 'Knee'                              WHERE name = 'Standing Quad Stretch';
UPDATE public.exercises SET body_parts = 'Knee'                              WHERE name = 'Prone Knee Flexion (Quad Stretch)';
UPDATE public.exercises SET body_parts = 'Knee, Hip'                         WHERE name = 'Seated Hamstring Stretch';
UPDATE public.exercises SET body_parts = 'Knee, Hip'                         WHERE name = 'Standing Hamstring Stretch';
UPDATE public.exercises SET body_parts = 'Hip'                               WHERE name = 'Clamshells';
UPDATE public.exercises SET body_parts = 'Hip'                               WHERE name = 'Side-Lying Hip Abduction';
UPDATE public.exercises SET body_parts = 'Hip, Core & Low Back'              WHERE name = 'Glute Bridges';
UPDATE public.exercises SET body_parts = 'Hip, Core & Low Back'              WHERE name = 'Single Leg Glute Bridge';
UPDATE public.exercises SET body_parts = 'Hip'                               WHERE name = 'Hip Flexor Stretch (Kneeling)';
UPDATE public.exercises SET body_parts = 'Hip'                               WHERE name = 'Piriformis Stretch (Figure-4)';
UPDATE public.exercises SET body_parts = 'Hip, Knee'                         WHERE name = 'IT Band Stretch';
UPDATE public.exercises SET body_parts = 'Hip'                               WHERE name = 'Hip Adductor (Groin) Stretch';
UPDATE public.exercises SET body_parts = 'Hip, Knee'                         WHERE name = 'Lateral Band Walks';
UPDATE public.exercises SET body_parts = 'Hip, Knee'                         WHERE name = 'Monster Walks';
UPDATE public.exercises SET body_parts = 'Hip, Core & Low Back'              WHERE name = 'Hip Hinge / Romanian Deadlift';
UPDATE public.exercises SET body_parts = 'Hip, Core & Low Back'              WHERE name = 'Prone Hip Extension';
UPDATE public.exercises SET body_parts = 'Hip'                               WHERE name = 'Standing Hip Flexion with Band';
UPDATE public.exercises SET body_parts = 'Hip'                               WHERE name = 'Theraband Hip Abduction (Standing)';
UPDATE public.exercises SET body_parts = 'Hip'                               WHERE name = 'Theraband Hip Extension (Standing)';
UPDATE public.exercises SET body_parts = 'Hip'                               WHERE name = 'Supine Hip External Rotation Stretch';
UPDATE public.exercises SET body_parts = 'Hip, Core & Low Back'              WHERE name = 'Copenhagen Adduction';
UPDATE public.exercises SET body_parts = 'Ankle & Foot'                      WHERE name = 'Ankle Pumps';
UPDATE public.exercises SET body_parts = 'Ankle & Foot'                      WHERE name = 'Ankle Circles';
UPDATE public.exercises SET body_parts = 'Ankle & Foot'                      WHERE name = 'Theraband Ankle Dorsiflexion';
UPDATE public.exercises SET body_parts = 'Ankle & Foot'                      WHERE name = 'Theraband Ankle Plantarflexion';
UPDATE public.exercises SET body_parts = 'Ankle & Foot'                      WHERE name = 'Theraband Ankle Inversion';
UPDATE public.exercises SET body_parts = 'Ankle & Foot'                      WHERE name = 'Theraband Ankle Eversion';
UPDATE public.exercises SET body_parts = 'Ankle & Foot'                      WHERE name = 'Double Leg Calf Raises';
UPDATE public.exercises SET body_parts = 'Ankle & Foot'                      WHERE name = 'Single Leg Calf Raise';
UPDATE public.exercises SET body_parts = 'Ankle & Foot'                      WHERE name = 'Seated Calf Raise';
UPDATE public.exercises SET body_parts = 'Ankle & Foot'                      WHERE name = 'Standing Calf Stretch';
UPDATE public.exercises SET body_parts = 'Ankle & Foot'                      WHERE name = 'Soleus Stretch';
UPDATE public.exercises SET body_parts = 'Ankle & Foot, Hip'                 WHERE name = 'Single Leg Balance / Proprioception';
UPDATE public.exercises SET body_parts = 'Ankle & Foot'                      WHERE name = 'Towel Scrunches';
UPDATE public.exercises SET body_parts = 'Ankle & Foot'                      WHERE name = 'Balance Board Training';
UPDATE public.exercises SET body_parts = 'Shoulder'                          WHERE name = 'Shoulder Pendulum Exercises';
UPDATE public.exercises SET body_parts = 'Shoulder'                          WHERE name = 'Shoulder Flexion AROM';
UPDATE public.exercises SET body_parts = 'Shoulder'                          WHERE name = 'Shoulder Abduction AROM';
UPDATE public.exercises SET body_parts = 'Shoulder'                          WHERE name = 'Shoulder Internal Rotation with Band';
UPDATE public.exercises SET body_parts = 'Shoulder'                          WHERE name = 'Shoulder External Rotation with Band';
UPDATE public.exercises SET body_parts = 'Shoulder'                          WHERE name = 'Scaption (Shoulder Scapular Plane Elevation)';
UPDATE public.exercises SET body_parts = 'Shoulder, Upper Back & Thoracic'   WHERE name = 'Prone T (Horizontal Abduction)';
UPDATE public.exercises SET body_parts = 'Shoulder, Upper Back & Thoracic'   WHERE name = 'Prone Y Raises';
UPDATE public.exercises SET body_parts = 'Shoulder'                          WHERE name = 'Serratus Anterior Punch';
UPDATE public.exercises SET body_parts = 'Shoulder, Upper Back & Thoracic'   WHERE name = 'Scapular Retraction';
UPDATE public.exercises SET body_parts = 'Shoulder, Upper Back & Thoracic'   WHERE name = 'Wall Angels';
UPDATE public.exercises SET body_parts = 'Shoulder'                          WHERE name = 'Doorway Pec Stretch';
UPDATE public.exercises SET body_parts = 'Shoulder'                          WHERE name = 'Shoulder Cross-Body Stretch';
UPDATE public.exercises SET body_parts = 'Shoulder, Upper Back & Thoracic'   WHERE name = 'Rows with Resistance Band';
UPDATE public.exercises SET body_parts = 'Shoulder, Upper Back & Thoracic'   WHERE name = 'Seated Row with Band';
UPDATE public.exercises SET body_parts = 'Shoulder'                          WHERE name = 'Shoulder Press with Band';
UPDATE public.exercises SET body_parts = 'Elbow, Wrist & Hand'               WHERE name = 'Bicep Curls with Band';
UPDATE public.exercises SET body_parts = 'Elbow, Wrist & Hand'               WHERE name = 'Tricep Extensions';
UPDATE public.exercises SET body_parts = 'Shoulder, Elbow, Wrist & Hand'     WHERE name = 'Wall Push-Ups';
UPDATE public.exercises SET body_parts = 'Shoulder, Elbow, Wrist & Hand, Core & Low Back' WHERE name = 'Push-Ups';
UPDATE public.exercises SET body_parts = 'Shoulder'                          WHERE name = 'Shoulder Sleeper Stretch';
UPDATE public.exercises SET body_parts = 'Elbow, Wrist & Hand'               WHERE name = 'Wrist Flexor Stretch';
UPDATE public.exercises SET body_parts = 'Elbow, Wrist & Hand'               WHERE name = 'Wrist Extensor Stretch';
UPDATE public.exercises SET body_parts = 'Elbow, Wrist & Hand'               WHERE name = 'Grip Strengthening';
UPDATE public.exercises SET body_parts = 'Elbow, Wrist & Hand'               WHERE name = 'Forearm Pronation and Supination';
UPDATE public.exercises SET body_parts = 'Core & Low Back'                   WHERE name = 'Pelvic Tilts';
UPDATE public.exercises SET body_parts = 'Core & Low Back, Hip'              WHERE name = 'Dead Bug';
UPDATE public.exercises SET body_parts = 'Core & Low Back, Hip'              WHERE name = 'Bird Dog';
UPDATE public.exercises SET body_parts = 'Core & Low Back'                   WHERE name = 'Plank';
UPDATE public.exercises SET body_parts = 'Core & Low Back, Hip'              WHERE name = 'Side Plank';
UPDATE public.exercises SET body_parts = 'Core & Low Back'                   WHERE name = 'Curl-Ups (Abdominal Crunch)';
UPDATE public.exercises SET body_parts = 'Core & Low Back, Upper Back & Thoracic' WHERE name = 'Cat-Cow Stretch';
UPDATE public.exercises SET body_parts = 'Upper Back & Thoracic, Core & Low Back' WHERE name = 'Thoracic Extension over Foam Roller';
UPDATE public.exercises SET body_parts = 'Core & Low Back'                   WHERE name = 'Supine Lumbar Rotation Stretch';
UPDATE public.exercises SET body_parts = 'Core & Low Back, Hip'              WHERE name = 'Knee to Chest Stretch';
UPDATE public.exercises SET body_parts = 'Core & Low Back'                   WHERE name = 'Double Knee to Chest';
UPDATE public.exercises SET body_parts = 'Core & Low Back, Hip, Shoulder'    WHERE name = 'Child''s Pose';
UPDATE public.exercises SET body_parts = 'Core & Low Back'                   WHERE name = 'Cobra Stretch (McKenzie Press-Up)';
UPDATE public.exercises SET body_parts = 'Core & Low Back'                   WHERE name = 'Prone on Elbows (Sphinx)';
UPDATE public.exercises SET body_parts = 'Cervical (Neck)'                   WHERE name = 'Chin Tucks';
UPDATE public.exercises SET body_parts = 'Cervical (Neck)'                   WHERE name = 'Cervical Rotation Stretch';
UPDATE public.exercises SET body_parts = 'Cervical (Neck)'                   WHERE name = 'Cervical Lateral Flexion Stretch';
UPDATE public.exercises SET body_parts = 'Cervical (Neck), Shoulder'         WHERE name = 'Upper Trapezius Stretch';
UPDATE public.exercises SET body_parts = 'Cervical (Neck)'                   WHERE name = 'Levator Scapulae Stretch';
UPDATE public.exercises SET body_parts = 'Upper Back & Thoracic, Cervical (Neck)' WHERE name = 'Thoracic Rotation (Open Books)';
UPDATE public.exercises SET body_parts = 'Cervical (Neck)'                   WHERE name = 'Neck Isometrics';
UPDATE public.exercises SET body_parts = 'Knee'                              WHERE name = 'Foam Rolling - Quadriceps';
UPDATE public.exercises SET body_parts = 'Hip, Knee'                         WHERE name = 'Foam Rolling - IT Band';
UPDATE public.exercises SET body_parts = 'Upper Back & Thoracic'             WHERE name = 'Foam Rolling - Thoracic Spine';
UPDATE public.exercises SET body_parts = 'Ankle & Foot'                      WHERE name = 'Foam Rolling - Calves';
UPDATE public.exercises SET body_parts = 'Knee, Hip'                         WHERE name = 'Hamstring Eccentrics';
UPDATE public.exercises SET body_parts = 'Hip'                               WHERE name = 'Supine Hip Abduction with Band';
